# -*- coding: utf-8 -*-
"""austin_concerts_dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DN133Gx1TV6OBSglFjCjrCHwq8ASa6WE
"""

# austin_concerts_dashboard.py
import streamlit as st
import pandas as pd
from datetime import datetime, timedelta
import json
from pathlib import Path

# ==================== THEME & STYLING ====================
st.set_page_config(
    page_title="Austin Concerts",
    page_icon="🎸",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for cleaner design
st.markdown("""
<style>
    /* Priority badges */
    .badge {
        display: inline-block;
        padding: 4px 12px;
        border-radius: 12px;
        font-size: 0.85rem;
        font-weight: 600;
        margin-right: 8px;
    }

    .badge-urgent { background: #FF4B4B; color: white; }
    .badge-high { background: #FFA500; color: white; }
    .badge-medium { background: #FFD700; color: #1E1E1E; }
    .badge-low { background: #00D26A; color: white; }
    .badge-liked { background: #1DB954; color: white; }

    /* Table styling - LIGHT THEME */
    .summary-table {
        width: 100%;
        border-collapse: collapse;
        margin: 1rem 0;
        background: white;
        border-radius: 8px;
        overflow: hidden;
        border: 1px solid #E0E0E0;
    }

    .summary-table th {
        background: #F5F5F5;
        padding: 12px;
        text-align: left;
        font-weight: 600;
        border-bottom: 2px solid #D0D0D0;
        color: #333333;
        font-size: 0.9rem;
    }

    .summary-table td {
        padding: 10px 12px;
        border-bottom: 1px solid #E8E8E8;
        color: #1E1E1E;
    }

    .summary-table tbody tr:last-child td {
        border-bottom: none;
    }

    .summary-table tr:hover {
        background: #FAFAFA;
    }

    /* Card styling for detailed view */
    .concert-card {
        background: white;
        border-left: 4px solid;
        padding: 1.2rem;
        border-radius: 8px;
        margin-bottom: 1rem;
        border: 1px solid #E0E0E0;
    }

    .concert-card h3 {
        color: #1E1E1E;
    }

    .urgent { border-left-color: #FF4B4B; }
    .high { border-left-color: #FFA500; }
    .medium { border-left-color: #FFD700; }
    .low { border-left-color: #00D26A; }
    .liked { border-left-color: #1DB954; background: #F0F8F4; }

    /* Hide default streamlit elements */
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
</style>
""", unsafe_allow_html=True)

# ==================== LOAD PREFERENCES ====================
PREFS_FILE = 'preferences.json'

def load_preferences():
    if Path(PREFS_FILE).exists():
        with open(PREFS_FILE, 'r') as f:
            prefs = json.load(f)
            if 'swipe_history' not in prefs:
                prefs['swipe_history'] = []
            if 'liked' not in prefs:
                prefs['liked'] = []
            if 'disliked' not in prefs:
                prefs['disliked'] = []
            return prefs
    return {"liked": [], "disliked": [], "swipe_history": []}

prefs = load_preferences()

# ==================== LOAD DATA ====================
@st.cache_data
def load_data():
    df = pd.read_excel('my_concerts_20251102_2153.xlsx')
    df['date'] = pd.to_datetime(df['date'])
    df = df.drop_duplicates(subset=['event_id'])

    today = pd.Timestamp.now().normalize()
    df['days_until'] = (df['date'] - today).dt.days

    def get_priority(days):
        if days < 0:
            return 'PAST'
        elif days <= 7:
            return 'URGENT'
        elif days <= 30:
            return 'HIGH'
        elif days <= 90:
            return 'MEDIUM'
        else:
            return 'LOW'

    df['priority_tier'] = df['days_until'].apply(get_priority)
    return df

df = load_data()

# ==================== HEADER ====================
col1, col2 = st.columns([3, 1])
with col1:
    st.title("Austin Live Music")
    st.caption("Your personalized concert calendar")
with col2:
    if st.button("🎵 Discover Artists", type="primary", use_container_width=True):
        st.switch_page("pages/artist_swipe.py")

st.markdown("---")

# ==================== SIDEBAR FILTERS ====================
st.sidebar.header("Filters")

# Preference filter
show_preference_filter = st.sidebar.checkbox(
    "Apply artist preferences",
    value=True,
    help="Hide passed artists, highlight liked"
)

st.sidebar.markdown("---")

# Date filter
date_option = st.sidebar.radio(
    "Time Period",
    ["Next 7 Days", "Next 30 Days", "Next 3 Months", "All Upcoming"],
    index=1
)

today = datetime.now().date()
if date_option == "Next 7 Days":
    end_date = today + timedelta(days=7)
elif date_option == "Next 30 Days":
    end_date = today + timedelta(days=30)
elif date_option == "Next 3 Months":
    end_date = today + timedelta(days=90)
else:
    end_date = df['date'].max().date()

filtered_df = df[(df['date'].dt.date >= today) & (df['date'].dt.date <= end_date)].copy()

# Apply preferences
if show_preference_filter and prefs['disliked']:
    filtered_df = filtered_df[~filtered_df['artist'].isin(prefs['disliked'])]

filtered_df['is_liked'] = filtered_df['artist'].isin(prefs['liked'])

# Venue filter
venues = ['All Venues'] + sorted(filtered_df['venue'].dropna().unique().tolist())
selected_venue = st.sidebar.selectbox("Venue", venues)
if selected_venue != 'All Venues':
    filtered_df = filtered_df[filtered_df['venue'] == selected_venue]

# Artist search
search = st.sidebar.text_input("Search Artist", "")
if search:
    filtered_df = filtered_df[filtered_df['artist'].str.contains(search, case=False, na=False)]

# Priority filter
priorities = st.sidebar.multiselect(
    "Priority Levels",
    ["URGENT", "HIGH", "MEDIUM", "LOW"],
    default=["URGENT", "HIGH", "MEDIUM", "LOW"]
)
filtered_df = filtered_df[filtered_df['priority_tier'].isin(priorities)]

# Liked only toggle
show_liked_only = st.sidebar.checkbox("Liked artists only", value=False)
if show_liked_only:
    filtered_df = filtered_df[filtered_df['is_liked']]

# ==================== SUMMARY STATISTICS TABLE ====================
st.subheader(f"Showing {len(filtered_df)} Concerts")

# Calculate stats
urgent_count = len(filtered_df[filtered_df['priority_tier'] == 'URGENT'])
high_count = len(filtered_df[filtered_df['priority_tier'] == 'HIGH'])
medium_count = len(filtered_df[filtered_df['priority_tier'] == 'MEDIUM'])
low_count = len(filtered_df[filtered_df['priority_tier'] == 'LOW'])
liked_count = len(filtered_df[filtered_df['is_liked']])
hidden_count = len(df[df['artist'].isin(prefs['disliked'])])

col1, col2 = st.columns([2, 1])

with col1:
    st.markdown("**Concert Timeline**")
    st.markdown(f"""
    <table class="summary-table">
        <thead>
            <tr>
                <th>Priority Level</th>
                <th style="text-align: right;">Concerts</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Urgent (≤7 days)</td>
                <td style="text-align: right;"><strong>{urgent_count}</strong></td>
            </tr>
            <tr>
                <td>High (7-30 days)</td>
                <td style="text-align: right;"><strong>{high_count}</strong></td>
            </tr>
            <tr>
                <td>Medium (1-3 months)</td>
                <td style="text-align: right;"><strong>{medium_count}</strong></td>
            </tr>
            <tr>
                <td>Low (3+ months)</td>
                <td style="text-align: right;"><strong>{low_count}</strong></td>
            </tr>
        </tbody>
    </table>
    """, unsafe_allow_html=True)

with col2:
    if show_preference_filter:
        st.markdown("**Your Preferences**")
        st.markdown(f"""
        <table class="summary-table">
            <thead>
                <tr>
                    <th>Type</th>
                    <th style="text-align: right;">#</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Liked</td>
                    <td style="text-align: right;"><strong>{liked_count}</strong></td>
                </tr>
                <tr>
                    <td>Hidden</td>
                    <td style="text-align: right;"><strong>{hidden_count}</strong></td>
                </tr>
            </tbody>
        </table>
        """, unsafe_allow_html=True)

st.markdown("---")

# ==================== CONCERT LIST ====================
if len(filtered_df) == 0:
    st.info("No concerts match your filters")
else:
    filtered_df = filtered_df.sort_values('date')

    # View options
    view_mode = st.radio(
        "View Mode",
        ["Compact", "Detailed"],
        horizontal=True,
        label_visibility="collapsed"
    )

    st.markdown("")

    for _, row in filtered_df.iterrows():
        priority_class = row['priority_tier'].lower()

        if view_mode == "Compact":
            # Compact view - one line
            col1, col2, col3, col4, col5 = st.columns([3, 2, 2, 1, 1])

            with col1:
                artist_display = f"**{row['artist']}**"
                if row['is_liked']:
                    artist_display = f"✓ {artist_display}"
                st.markdown(artist_display)

            with col2:
                st.markdown(f"{row['venue']}")

            with col3:
                st.markdown(f"{row['date'].strftime('%b %d, %Y')}")

            with col4:
                days = row['days_until']
                if days == 0:
                    st.markdown("**Today**")
                elif days == 1:
                    st.markdown("Tomorrow")
                else:
                    st.markdown(f"{days}d")

            with col5:
                if pd.notna(row.get('ticket_link')):
                    st.link_button("Tix", row['ticket_link'], use_container_width=True)

            st.divider()

        else:
            # Detailed view - card style
            card_class = "liked" if row['is_liked'] else priority_class

            # Format time safely
            time_display = row.get('time', 'TBA')
            if pd.notna(time_display):
                time_str = str(time_display)
            else:
                time_str = 'TBA'

            # Escape HTML characters in text
            artist_safe = str(row['artist']).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            venue_safe = str(row['venue']).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

            st.markdown(f"""
<div class="concert-card {card_class}">
    <div style="display: flex; justify-content: space-between; align-items: start;">
        <div style="flex: 1;">
            <h3 style="margin: 0 0 0.5rem 0; color: #1E1E1E;">{artist_safe}</h3>
            <p style="margin: 0.25rem 0; color: #555; line-height: 1.6;">
                📍 {venue_safe}<br>
                📅 {row['date'].strftime('%A, %B %d, %Y')}<br>
                ⏰ {time_str}
            </p>
        </div>
        <div style="text-align: right; margin-left: 1rem;">
            <span class="badge badge-{priority_class}">{row['priority_tier']}</span>{'<br><span class="badge badge-liked" style="margin-top: 0.5rem;">LIKED</span>' if row['is_liked'] else ''}
        </div>
    </div>
</div>
            """, unsafe_allow_html=True)

            # Ticket button outside the card HTML
            if pd.notna(row.get('ticket_link')):
                st.link_button("🎟️ Get Tickets", row['ticket_link'])

            st.markdown("")

# ==================== SIDEBAR STATS ====================
st.sidebar.markdown("---")
st.sidebar.markdown("### Overview")
st.sidebar.metric("Total Upcoming", len(df[df['priority_tier'] != 'PAST']))
st.sidebar.metric("Unique Venues", df['venue'].nunique())

if show_preference_filter:
    st.sidebar.markdown("---")
    st.sidebar.markdown("### Artist Preferences")
    st.sidebar.metric("Liked", len(prefs['liked']))
    st.sidebar.metric("Passed", len(prefs['disliked']))