# -*- coding: utf-8 -*-
"""artist-swipe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXaVYZ3CB-QaqUgg5VdQeSiTPbyYnUBW
"""

# artist-swipe.py
import streamlit as st
import json
import pandas as pd
from pathlib import Path
import requests
import base64
from urllib.parse import quote

st.set_page_config(page_title="Artist Swipe", page_icon="🎵", layout="wide")

# ==================== SPOTIFY API SETUP ====================
SPOTIFY_CLIENT_ID = "684f79d886db4d05829a92140ea463c1"
SPOTIFY_CLIENT_SECRET = "42a5ba77b17a4bd9934cfe12d37a4a7c"

def get_spotify_token():
    """Get Spotify access token"""
    auth_string = f"{SPOTIFY_CLIENT_ID}:{SPOTIFY_CLIENT_SECRET}"
    auth_bytes = auth_string.encode("utf-8")
    auth_base64 = base64.b64encode(auth_bytes).decode("utf-8")

    url = "https://accounts.spotify.com/api/token"
    headers = {
        "Authorization": f"Basic {auth_base64}",
        "Content-Type": "application/x-www-form-urlencoded"
    }
    data = {"grant_type": "client_credentials"}

    response = requests.post(url, headers=headers, data=data)
    return response.json()["access_token"]

@st.cache_data(ttl=3600)
def search_artist_spotify(artist_name, token):
    """Search for artist on Spotify and get their info"""
    url = "https://api.spotify.com/v1/search"
    headers = {"Authorization": f"Bearer {token}"}
    params = {
        "q": artist_name,
        "type": "artist",
        "limit": 1
    }

    response = requests.get(url, headers=headers, params=params)
    data = response.json()

    if data['artists']['items']:
        artist = data['artists']['items'][0]
        return {
            "name": artist['name'],
            "image": artist['images'][0]['url'] if artist['images'] else None,
            "genres": artist['genres'][:3],
            "popularity": artist['popularity'],
            "followers": artist['followers']['total'],
            "spotify_url": artist['external_urls']['spotify'],
            "spotify_id": artist['id']
        }
    return None

@st.cache_data(ttl=3600)
def get_artist_top_tracks(artist_id, token, limit=10):
    """Get artist's top tracks with preview URLs"""
    url = f"https://api.spotify.com/v1/artists/{artist_id}/top-tracks"
    headers = {"Authorization": f"Bearer {token}"}
    params = {"market": "US"}

    response = requests.get(url, headers=headers, params=params)
    tracks = response.json().get('tracks', [])

    return [{
        "name": track['name'],
        "artist": track['artists'][0]['name'],
        "preview_url": track['preview_url'],
        "album_image": track['album']['images'][0]['url'] if track['album']['images'] else None,
        "spotify_url": track['external_urls']['spotify'],
        "album_name": track['album']['name']
    } for track in tracks[:limit]]

@st.cache_data(ttl=3600)
def get_artist_albums(artist_id, token):
    """Get artist's albums"""
    url = f"https://api.spotify.com/v1/artists/{artist_id}/albums"
    headers = {"Authorization": f"Bearer {token}"}
    params = {"market": "US", "limit": 5, "include_groups": "album,single"}

    response = requests.get(url, headers=headers, params=params)
    albums = response.json().get('items', [])

    return [{
        "name": album['name'],
        "image": album['images'][0]['url'] if album['images'] else None,
        "release_date": album['release_date'],
        "spotify_url": album['external_urls']['spotify']
    } for album in albums]

def get_youtube_search_url(artist_name, track_name):
    """Generate YouTube search URL for a track"""
    query = f"{artist_name} {track_name} official audio"
    return f"https://www.youtube.com/results?search_query={quote(query)}"

# ==================== FILE MANAGEMENT ====================
EXCEL_FILE = 'my_concerts_20251102_2153.xlsx'
PREFS_FILE = 'preferences.json'

def load_preferences():
    if Path(PREFS_FILE).exists():
        with open(PREFS_FILE, 'r') as f:
            prefs = json.load(f)
            # Ensure all required keys exist (for backward compatibility)
            if 'swipe_history' not in prefs:
                prefs['swipe_history'] = []
            if 'liked' not in prefs:
                prefs['liked'] = []
            if 'disliked' not in prefs:
                prefs['disliked'] = []
            return prefs
    return {"liked": [], "disliked": [], "swipe_history": []}

def save_preferences(prefs):
    with open(PREFS_FILE, 'w') as f:
        json.dump(prefs, f, indent=2)

@st.cache_data
def load_concerts():
    df = pd.read_excel(EXCEL_FILE)
    df = df.drop_duplicates(subset=['event_id'])
    return df

# ==================== SESSION STATE ====================
if 'prefs' not in st.session_state:
    st.session_state.prefs = load_preferences()

if 'current_idx' not in st.session_state:
    st.session_state.current_idx = 0

if 'artists_list' not in st.session_state:
    df = load_concerts()
    all_artists = df['artist'].drop_duplicates().dropna().tolist()
    already_rated = st.session_state.prefs['liked'] + st.session_state.prefs['disliked']
    st.session_state.artists_list = [a for a in all_artists if a not in already_rated]

if 'spotify_token' not in st.session_state:
    try:
        st.session_state.spotify_token = get_spotify_token()
    except:
        st.error("⚠️ Spotify API credentials not configured.")
        st.session_state.spotify_token = None

if 'show_review_page' not in st.session_state:
    st.session_state.show_review_page = False

# ==================== REVIEW & EDIT PAGE ====================
if st.session_state.show_review_page:
    st.title("📝 Review & Edit Your Choices")

    # Back button
    if st.button("⬅️ Back to Swiping"):
        st.session_state.show_review_page = False
        st.rerun()

    st.markdown("---")

    # Two columns for liked and disliked
    col1, col2 = st.columns(2)

    with col1:
        st.markdown(f"### ✅ Liked Artists ({len(st.session_state.prefs['liked'])})")

        if st.session_state.prefs['liked']:
            for i, artist in enumerate(sorted(st.session_state.prefs['liked'])):
                col_a, col_b = st.columns([3, 1])
                with col_a:
                    st.markdown(f"**{artist}**")
                with col_b:
                    if st.button("❌", key=f"unlike_{i}", help="Move to Passed"):
                        st.session_state.prefs['liked'].remove(artist)
                        st.session_state.prefs['disliked'].append(artist)
                        save_preferences(st.session_state.prefs)
                        st.rerun()
        else:
            st.caption("No liked artists yet")

    with col2:
        st.markdown(f"### ❌ Passed Artists ({len(st.session_state.prefs['disliked'])})")

        if st.session_state.prefs['disliked']:
            for i, artist in enumerate(sorted(st.session_state.prefs['disliked'])):
                col_a, col_b = st.columns([3, 1])
                with col_a:
                    st.markdown(f"**{artist}**")
                with col_b:
                    if st.button("✅", key=f"relike_{i}", help="Move to Liked"):
                        st.session_state.prefs['disliked'].remove(artist)
                        st.session_state.prefs['liked'].append(artist)
                        save_preferences(st.session_state.prefs)
                        st.rerun()
        else:
            st.caption("No passed artists yet")

    st.stop()

# ==================== MAIN UI ====================
st.title("🎵 Discover Artists")
st.markdown("### Swipe to build your concert preferences")

# Helpful tip
st.info("💡 **Tip:** Review anytime using the sidebar • Progress auto-saves • Made a mistake? Use Undo!")

# Progress
total_artists = len(st.session_state.artists_list)
progress = st.session_state.current_idx / max(total_artists, 1)

# Top metrics
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Progress", f"{st.session_state.current_idx + 1}/{total_artists}")
with col2:
    st.metric("✅ Liked", len(st.session_state.prefs['liked']))
with col3:
    st.metric("❌ Passed", len(st.session_state.prefs['disliked']))
with col4:
    remaining = total_artists - st.session_state.current_idx
    st.metric("Remaining", remaining)

st.progress(progress)

# Check if done
if st.session_state.current_idx >= total_artists:
    st.success("🎉 You've reviewed all artists!")
    st.balloons()

    col1, col2 = st.columns(2)
    with col1:
        st.metric("✅ Total Liked", len(st.session_state.prefs['liked']))
    with col2:
        st.metric("❌ Total Passed", len(st.session_state.prefs['disliked']))

    col_a, col_b = st.columns(2)
    with col_a:
        if st.button("🔄 Reset and Start Over", use_container_width=True):
            st.session_state.prefs = {"liked": [], "disliked": [], "swipe_history": []}
            st.session_state.current_idx = 0
            save_preferences(st.session_state.prefs)
            st.rerun()
    with col_b:
        if st.button("📝 Review Choices", use_container_width=True, type="primary"):
            st.session_state.show_review_page = True
            st.rerun()

    st.stop()

# Current artist
artist = st.session_state.artists_list[st.session_state.current_idx]
df = load_concerts()
artist_shows = df[df['artist'] == artist].sort_values('date')
show_count = len(artist_shows)
next_show = artist_shows.iloc[0] if show_count > 0 else None

# ==================== SPOTIFY DATA ====================
spotify_data = None
top_tracks = []
albums = []

if st.session_state.spotify_token:
    with st.spinner("Loading artist info..."):
        spotify_data = search_artist_spotify(artist, st.session_state.spotify_token)
        if spotify_data:
            top_tracks = get_artist_top_tracks(spotify_data['spotify_id'], st.session_state.spotify_token, limit=10)
            albums = get_artist_albums(spotify_data['spotify_id'], st.session_state.spotify_token)

# ==================== ARTIST CARD ====================
st.markdown("---")

col_img, col_info = st.columns([1, 2])

with col_img:
    if spotify_data and spotify_data['image']:
        st.image(spotify_data['image'], use_container_width=True)
    else:
        st.markdown("### 🎤")
        st.markdown(f"**{artist}**")

with col_info:
    st.markdown(f"## {artist}")

    if spotify_data and spotify_data['genres']:
        genre_tags = " ".join([f"`{g}`" for g in spotify_data['genres']])
        st.markdown(f"**Genres:** {genre_tags}")

    if spotify_data:
        st.markdown(f"**Popularity:** {spotify_data['popularity']}/100")
        st.progress(spotify_data['popularity'] / 100)
        st.markdown(f"👥 **{spotify_data['followers']:,} followers**")
        st.markdown(f"[🎵 Listen on Spotify]({spotify_data['spotify_url']})")

    st.markdown("---")
    if next_show is not None:
        date_obj = pd.to_datetime(next_show['date'])
        st.markdown(f"📅 **Next Show:** {date_obj.strftime('%b %d, %Y')}")
        st.markdown(f"📍 **Venue:** {next_show['venue']}")
        st.markdown(f"🎫 **Upcoming Shows:** {show_count}")

# ==================== RECENT ALBUMS ====================
if albums:
    st.markdown("---")
    st.markdown("### 💿 Recent Albums")
    cols = st.columns(len(albums))
    for i, album in enumerate(albums):
        with cols[i]:
            if album['image']:
                st.image(album['image'], use_container_width=True)
            st.caption(album['name'])
            st.caption(album['release_date'][:4])

# ==================== TOP TRACKS WITH TABS ====================
if top_tracks:
    st.markdown("---")

    # Count tracks with previews
    previews_available = sum(1 for t in top_tracks if t['preview_url'])
    st.markdown(f"### 🎧 Popular Tracks ({previews_available}/{len(top_tracks)} previews available)")

    # Create tabs for better organization
    tab1, tab2 = st.tabs(["🔥 Top 5", "📚 All Tracks"])

    with tab1:
        st.caption("Their most popular songs")
        for i, track in enumerate(top_tracks[:5]):
            with st.container():
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.markdown(f"**{i+1}. {track['name']}**")
                    st.caption(f"From: {track['album_name']}")

                    if track['preview_url']:
                        st.audio(track['preview_url'], format="audio/mp3")
                    else:
                        youtube_url = get_youtube_search_url(track['artist'], track['name'])
                        col_a, col_b = st.columns(2)
                        with col_a:
                            st.link_button("🎵 Play on Spotify", track['spotify_url'], use_container_width=True)
                        with col_b:
                            st.link_button("▶️ Find on YouTube", youtube_url, use_container_width=True)

                with col2:
                    if track['album_image']:
                        st.image(track['album_image'], width=80)
                st.markdown("")

    with tab2:
        st.caption("All top 10 tracks")
        for i, track in enumerate(top_tracks):
            with st.container():
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.markdown(f"**{i+1}. {track['name']}**")
                    st.caption(f"From: {track['album_name']}")

                    if track['preview_url']:
                        st.audio(track['preview_url'], format="audio/mp3")
                    else:
                        youtube_url = get_youtube_search_url(track['artist'], track['name'])
                        col_a, col_b = st.columns(2)
                        with col_a:
                            st.link_button("🎵 Spotify", track['spotify_url'], use_container_width=True)
                        with col_b:
                            st.link_button("▶️ YouTube", youtube_url, use_container_width=True)

                with col2:
                    if track['album_image']:
                        st.image(track['album_image'], width=80)
                st.markdown("")

# ==================== ACTION BUTTONS ====================
st.markdown("---")

# Add undo and save buttons
col_undo, col_save = st.columns([1, 1])

with col_undo:
    # Undo button (only show if we've made at least one swipe)
    if st.session_state.current_idx > 0:
        if st.button("↩️ Undo Last Swipe", use_container_width=True, type="secondary"):
            # Get the last artist we rated
            last_history = st.session_state.prefs['swipe_history'][-1] if st.session_state.prefs['swipe_history'] else None

            if last_history:
                last_artist = last_history['artist']
                last_action = last_history['action']

                # Remove from liked or disliked
                if last_action == 'liked' and last_artist in st.session_state.prefs['liked']:
                    st.session_state.prefs['liked'].remove(last_artist)
                elif last_action == 'disliked' and last_artist in st.session_state.prefs['disliked']:
                    st.session_state.prefs['disliked'].remove(last_artist)

                # Remove from history
                st.session_state.prefs['swipe_history'].pop()

                # Go back one artist
                st.session_state.current_idx -= 1

                save_preferences(st.session_state.prefs)
                st.rerun()

with col_save:
    if st.button("💾 Save & Exit for Now", use_container_width=True, type="secondary"):
        save_preferences(st.session_state.prefs)
        st.success(f"✅ Progress saved! Reviewed {st.session_state.current_idx} of {total_artists}")
        st.info("Come back anytime to continue!")
        st.stop()

st.markdown("")

# Main swipe buttons
col1, col2, col3 = st.columns([1, 1, 1])

with col1:
    if st.button("❌ Pass", use_container_width=True, type="secondary", key="pass"):
        st.session_state.prefs['disliked'].append(artist)
        st.session_state.prefs['swipe_history'].append({
            "artist": artist,
            "action": "disliked",
            "timestamp": pd.Timestamp.now().isoformat()
        })
        st.session_state.current_idx += 1
        save_preferences(st.session_state.prefs)
        st.rerun()

with col2:
    st.markdown("<div style='text-align: center; padding-top: 8px;'>Click buttons to swipe!</div>",
                unsafe_allow_html=True)

with col3:
    if st.button("✅ Like", use_container_width=True, type="primary", key="like"):
        st.session_state.prefs['liked'].append(artist)
        st.session_state.prefs['swipe_history'].append({
            "artist": artist,
            "action": "liked",
            "timestamp": pd.Timestamp.now().isoformat()
        })
        st.session_state.current_idx += 1
        save_preferences(st.session_state.prefs)
        st.rerun()

# ==================== SIDEBAR STATS ====================
with st.sidebar:
    st.markdown("### 📊 Your Stats")
    st.metric("✅ Liked Artists", len(st.session_state.prefs['liked']))
    st.metric("❌ Passed Artists", len(st.session_state.prefs['disliked']))

    st.markdown("---")

    # Review button in sidebar
    if st.button("📝 Review & Edit All Choices", use_container_width=True, type="primary"):
        st.session_state.show_review_page = True
        st.rerun()

    st.markdown("---")

    if st.session_state.prefs['liked']:
        st.markdown("#### 💚 Recent Likes:")
        for liked_artist in st.session_state.prefs['liked'][-5:]:
            st.markdown(f"✓ {liked_artist}")

    st.markdown("---")
    st.caption("💡 Progress auto-saves after each swipe!")
    st.caption("🎵 No preview? Click Spotify/YouTube links!")
    st.caption("↩️ Made a mistake? Use 'Undo' button!")

    if st.button("🏠 Back to Dashboard"):
        st.switch_page("austin_concerts_dashboard.py")